version: '3.6'

services:
  twitterwipe:
    build: .
    container_name: twitterwipe
    environment:
      APP_KEY: ${APP_KEY}
      APP_SECRET: ${APP_SECRET}
      CONSUMER_KEY: ${CONSUMER_KEY}
      CONSUMER_SECRET: ${CONSUMER_SECRET}
      COMMAND: ${COMMAND}
      ARGS: ${ARGS}
      TZ: ${TZ}
    volumes:
      - ./keys.json:/twitterwipe/keys.json
      - ./like.js:/twitterwipe/like.js
      - ./tweet.js:/twitterwipe/tweet.js
      - ./config.yaml:/twitterwipe/config.yaml
      - ./log.log:/twitterwipe/log.log
